from __future__ import annotations

import argparse
import math
import time
from pathlib import Path

import rclpy
from nav_msgs.msg import OccupancyGrid
from rclpy.node import Node
from rclpy.qos import DurabilityPolicy, HistoryPolicy, QoSProfile, ReliabilityPolicy
from std_msgs.msg import String

from .common import loads_dict


def _inverse_pixel_transform(
    *,
    origin_x: float,
    origin_y: float,
    res: float,
    map_x: float,
    map_y: float,
    map_yaw: float,
) -> tuple[float, float, float]:
    # Desired pixel transform places a robot grid in the reference map:
    # p_ref_px = R(map_yaw) * p_grid_px + (R * origin + t) / res.
    # multirobot_map_merge/GridWarper expects the inverse affine.
    c = math.cos(map_yaw)
    s = math.sin(map_yaw)
    dx = (c * origin_x - s * origin_y + map_x) / res
    dy = (s * origin_x + c * origin_y + map_y) / res
    inv_yaw = -map_yaw
    ci = math.cos(inv_yaw)
    si = math.sin(inv_yaw)
    tx = -(ci * dx - si * dy)
    ty = -(si * dx + ci * dy)
    return tx, ty, inv_yaw


class DiscoveredMapMergeBootstrap(Node):
    """Wait for discovered relative pose, then write map_merge params once."""

    def __init__(self, args: argparse.Namespace) -> None:
        super().__init__("discovered_map_merge_bootstrap_node")
        self.args = args
        self.maps: dict[str, OccupancyGrid | None] = {r: None for r in args.robots}
        self.status: dict | None = None
        self._subs = []
        map_qos = QoSProfile(
            depth=1,
            reliability=ReliabilityPolicy.RELIABLE,
            durability=DurabilityPolicy.TRANSIENT_LOCAL,
            history=HistoryPolicy.KEEP_LAST,
        )
        for robot in args.robots:
            topic = f"/{robot}/{args.map_topic_suffix.lstrip('/')}"
            self._subs.append(self.create_subscription(
                OccupancyGrid, topic, lambda msg, r=robot: self._on_map(r, msg), map_qos))
            self.get_logger().info(f"waiting for {topic}")
        self.create_subscription(String, args.alignment_status_topic, self._on_status, 10)
        self.get_logger().info(f"waiting for aligned status on {args.alignment_status_topic}")

    def _on_map(self, robot: str, msg: OccupancyGrid) -> None:
        if self.maps[robot] is None:
            self.get_logger().info(
                f"MAP {robot}: origin=({msg.info.origin.position.x:.3f}, "
                f"{msg.info.origin.position.y:.3f}) res={msg.info.resolution:.3f}"
            )
        self.maps[robot] = msg

    def _on_status(self, msg: String) -> None:
        payload = loads_dict(msg.data)
        if payload and payload.get("schema") == "team_alignment_status/v1":
            self.status = payload

    def ready(self) -> bool:
        if not all(m is not None for m in self.maps.values()):
            return False
        return bool(self.status and self.status.get("status") == "aligned")

    def write_yaml(self) -> None:
        assert self.status is not None
        if len(self.args.robots) != 2:
            raise RuntimeError("discovered bootstrap currently expects exactly two robots")
        ref, other = self.args.robots
        transform = self.status.get("transform", {})
        rel_x = float(transform.get("x", 0.0))
        rel_y = float(transform.get("y", 0.0))
        rel_yaw = float(transform.get("yaw", 0.0))
        lines = [
            "# Auto-generated by discovered_map_merge_bootstrap_node; do not edit.",
            "# Uses /team_slam/alignment_status, not MuJoCo ground truth.",
            "map_merge:",
            "  ros__parameters:",
            "    known_init_poses: true",
            "    track_map_origin: false",
            f"    merging_rate: {self.args.merging_rate}",
            f"    discovery_rate: {self.args.discovery_rate}",
            "    estimation_rate: 0.5",
            "    estimation_confidence: 0.6",
            "    robot_map_topic: map",
            "    robot_map_updates_topic: map_updates",
            '    robot_namespace: ""',
            f"    merged_map_topic: {self.args.merged_map_topic}",
            "    world_frame: world",
            "",
        ]
        for robot in self.args.robots:
            msg = self.maps[robot]
            assert msg is not None
            res = float(msg.info.resolution)
            if res <= 1e-6:
                raise RuntimeError(f"{robot} map has invalid resolution {res}")
            origin = msg.info.origin.position
            if robot == ref:
                x_px, y_px, yaw = _inverse_pixel_transform(
                    origin_x=float(origin.x), origin_y=float(origin.y),
                    res=res, map_x=0.0, map_y=0.0, map_yaw=0.0)
            else:
                x_px, y_px, yaw = _inverse_pixel_transform(
                    origin_x=float(origin.x), origin_y=float(origin.y),
                    res=res, map_x=rel_x, map_y=rel_y, map_yaw=rel_yaw)
            lines.append(f"    /{robot}/map_merge/init_pose_x: {x_px:.6f}")
            lines.append(f"    /{robot}/map_merge/init_pose_y: {y_px:.6f}")
            lines.append("    /{}/map_merge/init_pose_z: 0.0".format(robot))
            lines.append(f"    /{robot}/map_merge/init_pose_yaw: {yaw:.6f}")
        Path(self.args.output).write_text("\n".join(lines) + "\n")
        self.get_logger().info(f"wrote discovered map_merge params to {self.args.output}")


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--robots", nargs="+", default=["robot_a", "robot_b"])
    ap.add_argument("--alignment-status-topic", default="/team_slam/alignment_status")
    ap.add_argument("--map-topic-suffix", default="map")
    ap.add_argument("--output", required=True)
    ap.add_argument("--timeout-sec", type=float, default=180.0)
    ap.add_argument("--merged-map-topic", default="merged_map")
    ap.add_argument("--merging-rate", type=float, default=2.0)
    ap.add_argument("--discovery-rate", type=float, default=0.5)
    return ap.parse_args()


def main() -> int:
    args = parse_args()
    rclpy.init()
    node = DiscoveredMapMergeBootstrap(args)
    deadline = time.monotonic() + args.timeout_sec
    try:
        while rclpy.ok() and not node.ready():
            if time.monotonic() >= deadline:
                node.get_logger().error(
                    f"timed out waiting for discovered alignment and maps after {args.timeout_sec}s"
                )
                return 2
            rclpy.spin_once(node, timeout_sec=0.1)
        node.write_yaml()
        return 0
    except KeyboardInterrupt:
        return 130
    finally:
        node.destroy_node()
        rclpy.try_shutdown()


if __name__ == "__main__":
    raise SystemExit(main())
