common:
    lid_topic: "/velodyne_points"
    imu_topic: "/imu/data"
    con_frame: false
    con_frame_num: 1
    cut_frame: false
    cut_frame_time_interval: 0.1
    time_lag_imu_to_lidar: 0.0

preprocess:
    lidar_type: 2
    scan_line: 20
    timestamp_unit: 2
    blind: 0.40

mapping:
    imu_en: true
    start_in_aggressive_motion: false
    extrinsic_est_en: false
    imu_time_inte: 0.01
    satu_acc: 30.0
    satu_gyro: 35
    acc_norm: 9.81
    lidar_meas_cov: 0.01
    acc_cov_output: 500
    gyr_cov_output: 1000
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    imu_meas_acc_cov: 0.1
    imu_meas_omg_cov: 0.1
    gyr_cov_input: 0.01
    acc_cov_input: 0.1
    plane_thr: 0.1
    match_s: 81
    fov_degree: 360
    det_range: 20.0
    gravity_align: true
    gravity: [0.0, 0.0, -9.810]
    gravity_init: [0.0, 0.0, -9.810]
    extrinsic_T: [0.187, 0.0, 0.0803]
    extrinsic_R: [0.9744,  0.0, 0.2249,
                  0.0,     1.0, 0.0,
                 -0.2249,  0.0, 0.9744]

odometry:
    publish_odometry_without_downsample: false

publish:
    path_en: true
    scan_publish_en: true
    scan_bodyframe_pub_en: true

pcd_save:
    pcd_save_en: false
    interval: -1
